### ISSUE TITLE
GLTF Unsupported extensions

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#608]
**Context**
F3D using the vtkGLTFImporter to read glTF file and glb file.
However, that importer does not support all feature from the glTF standard.
Here is a list of feature that could be implemented in the importer, and, for some of them, in some parts of the rendering stack of VTK

- [ ] KHR_materials_clearcoat
- [x] KHR_texture_transform: https://github.com/f3d-app/f3d/issues/1696
- [ ] KHR_materials_pbrSpecularGlossiness: https://github.com/f3d-app/f3d/issues/943
- [ ] KHR_materials_specular
- [ ] KHR_materials_ior
- [ ] KHR_materials_transmission
- [ ] KHR_materials_volume
- [ ] KHR_texture_basisu: https://github.com/f3d-app/f3d/issues/1707
- [ ] KHR_meshopt_compression: https://github.com/f3d-app/f3d/issues/2850
- [ ] CESIUM_RTC: https://github.com/f3d-app/f3d/issues/1705

**Suggested solution**
 - Investigate the details of the standard for an extension
 - Implement the support in VTK for reading and rendering the extension

**Skills needed**
 - VTK

**Comment by zoofur** [comment]
I want to view the gltf file, but I encountered an unsupported extension(KHR_texture_transform).
What the plan is for supporting these extensions?

**Comment by zoofur** [comment]
> > I want to view the gltf file, but I encountered an unsupported extension(KHR_texture_transform). What the plan is for supporting these extensions?
> 
> The plan is to implement support for these extensions in the future, but there is no concrete milestone yet. If you are a C++ developer, we can guide you for the implementation of this feature :)

I got it.Thank you for your reply.

**Comment by mwestphal** [comment]
> > > I want to view the gltf file, but I encountered an unsupported extension(KHR_texture_transform). What the plan is for supporting these extensions?
> > 
> > 
> > The plan is to implement support for these extensions in the future, but there is no concrete milestone yet. If you are a C++ developer, we can guide you for the implementation of this feature :)
> 
> I got it.Thank you for your reply.

It is now supported @zoofur

**Comment by Meakk** [comment]
Ticked `KHR_materials_ior`, it's already implemented.
I'm working on `KHR_mesh_quantization`

**Comment by snoyer** [comment]
> I'm working on `KHR_mesh_quantization`

I've seen it in models exported from `three.js` so it would be nice to have.

`three.js` also uses `EXT_mesh_gpu_instancing`, could F3D/VTK instantiate actors based on this one?

**Comment by Meakk** [comment]
Yes GPU instancing is supported in VTK with the glyph mapper. It comes with some limitation though (like unique material for all the instance type)

**Comment by snoyer** [comment]
I'm not familiar enough with VTK or the extension spec to be able to tell if it would be able to do proper GPU instancing.
I was thinking any instancing at all (even if it's suboptimal copies in some cases) as long as it lets F3D show files that require `EXT_mesh_gpu_instancing` instead of just refusing to open them.

**Comment by Meakk** [comment]
I see. Sure that's something we can do. That's how we handle instancing for the USD format at the moment, but that doesn't scale well.
