### ISSUE TITLE
1.2.0 release

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#85]
1.2.0 Release

- [x] Fix remainings issues: 
  - [x] #37 
  - [x] #58 
  - [x] #73 
  - [x] #65 
  - [x] #60 
- [x] Last fixups: #95 
- [x] Update version strings: #96 
- [x] Write the changelog
- [x] Last fixups again: #100 
- [x] Generate communication images and gifs
- [x] Trigger a CI build
- [x] Download and quickly test Linux artifacts : run, render, drag&drop, thumbnails
- [x] Download and quickly test MacOS artifacts: run, render, drag&drop
- [x] Download and quickly test Windows artifacts: run, render, drag&drop, thumbnails
- [x] Generate google analytics: #105 
- [x] Update github-pages branch and check website
- [x] Merge website update: #112 
- [x] Cleanup repo
- [x] Tag the commit and push the tag
- [x] merge master into release
- [x] Create release on gitlab with changelog and artifacts
- [x] Update Aur package
- [x] Update Brew package: https://github.com/Homebrew/homebrew-core/pull/90575
- [x] Inform package maintainers
- [x] Inform Assimp team
- [x] Communicate LinkedIn
- [x] Communicate Reddit

**Comment by mwestphal** [comment]
@Meakk FYI, please let me know if I should add more items

**Comment by Meakk** [comment]
We can also inform Assimp we have integrated the library, it could be useful for them.

**Comment by mwestphal** [comment]
Release notes draft:

Main Features:
- Added STEP and IGES file format support thanks to @Open-Cascade-SAS/[OCCT](https://github.com/Open-Cascade-SAS/OCCT) (thanks @drtrigon)
- Added FBX, DAE, OFF, and DXF file format support thanks to @assimp/[assimp](https://github.com/assimp/assimp)
- Added thumbnail support with many linux file managers
- Added thumbnail support on Windows
- Added desktop environnement integration in linux
- Added scalar and scalar component looping

Other Features:
- Added support for KHR_materials_unlit with glTF files (thanks @spiraloid)
- Added option for selecting camera `--camera-index` (thanks @spiraloid)
- Added coloring the to Windows error output window
- Added a man entry on Linux
- Added a `--config` option to select a config file to load instead of using default location
- Added a `--quiet` option
- Added `--camera-azimuth` and `--camera-elevation` options (thanks @tatsuya-s)
- Added a metainfo.xml file (thanks @kevinsmia1939)

Issue Fixes:
- Fixed an issue with opening files with accented char in the name on Windows (thanks @shankarsivarajan)
- Fixed HDRI orientation with --up option (thanks @truhlikfredy)
- Fixed an issue with point cloud rendering
- Fixed a crash on exit on Windows
- Fixed an issue with fullscreen window size on Windows
- Fixed offscreen rendering (`--output` and `--ref` ) to actually use offscreen rendering
- Fixed a memory leak when no rendering is performed (thanks @CharlesGueunet)
- Fixed a rendering issue with certain GPU drivers
- Fixed tone mapping with background opacity
- Fixed non-working drag and drop implementation in VTK (thanks @msbit)
- Fixed a potential sorting issue when opening a folder
- Fixed a crash with unsupported glTF files in VTK

Contributors: @CharlesGueunet @kevinsmia1939 @mzf-guest @jpouderoux @Meakk @mwestphal

**Comment by mwestphal** [comment]
ongoing test on linux. Could you test on MacOS @Meakk ?

**Comment by Meakk** [comment]
MacOS validated

**Comment by mwestphal** [comment]
Best to worst type of post:
- Video post
- Image post
- Link post

Alqys mention that it is free and opensource.

Reddit communication planning:

STEP/IGES support focus:
/r/cad 
/r/CFD
/r/fosscad
/r/MechanicalEngineering
/r/CNC
/r/engineering

FBX/COLLADA support focus
/r/3Dmodeling
/r/GraphicsProgramming
/r/opengl
/r/computergraphics
/r/renderings
/r/gameenginedevs
/r/gamedev
/r/3DMA

Generic post:
/r/opensource
/r/3DScanning
/r/software
/r/coolgithubprojects
/r/3Dprinting
/r/gis
/r/lasercutting

**Comment by mwestphal** [comment]
[F3D](https://f3d-app.github.io/f3d/), the fast and minimalist open source 3D viewer just released its 1.2.0

Many new features and bug fixes have been added, the main ones being:

* STEP and IGES files support
* FBX, DXF, DAE, OFF files support
* Thumbnails integration in Windows and Linux
* Desktop integration in Windows, MacOS and Linux
* Scalars looping

As a reminder for those that are for the first time about F3D, it is a minimalist, efficient, interactive 3D viewer supporting many file formats (STEP, FBX, STL, glTF, ply, obj, 3ds, vt\*). It has a wide range of features, raytracing, volume rendering, sprites, camera positioning, color map, HDR textures, post fx options, coloring.

It can simply be downloaded from our [github](https://github.com/f3d-app/f3d/releases) as a binary package or installed with package managers, VTK, Assimp and OpenCascade being the main dependencies.

Please, have a look at the[ documentation](https://kitware.github.io/F3D/docs/) and the [gallery](https://f3d-app.github.io/f3d/gallery/). Feedbacks and contributions are very welcomed and issues can be freely opened on the githut repository.
You can also join our very new [f3d-app](https://www.reddit.com/r/f3d-app/) subreddit or even star us on github !

F3D can be very useful in the context of _stuff_ as it lets you quickly and effortlessly take a quick look at your meshes the same way you would take a look at an image using a simple image viewer.

**Comment by mzf-guest** [comment]
The documentation link (https://kitware.github.io/F3D/docs) returns 404 error.

**Comment by mwestphal** [comment]
where is this link ? it should have been updated in the context of #65

**Comment by mwestphal** [comment]
found it, thanks

**Comment by drtrigon** [comment]
Thanks for the DXF support! (and of course the STEP support also)

**Comment by drtrigon** [comment]
To emphasize this: to my knowledge this is the first lightweight viewer software that has support for all important CAD formats and allows to view them easily on all major OSes! Congratulation!

**Comment by Meakk** [comment]
Thanks @drtrigon we appreciate! 😄

**Comment by mwestphal** [comment]
Thanks @drtrigon ! much appreciated !

**Comment by Meakk** [comment]
@mwestphal I will probably skip 1.2.0 in Brew, and wait for 1.2.1. I guess we can close this issue

**Comment by mwestphal** [comment]
closing then
